name: Supabase Backup

on:
  schedule:
    - cron: "0 */4 * * *" # Runs every 4 hours
  workflow_dispatch: # Allows manual triggering

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Backup API
        run: |
          curl -X POST ${{ secrets.DEPLOYMENT_URL }}/api/backup \
          -H "Content-Type: application/json" \
          -H "Authorization: Bearer ${{ secrets.API_SECRET_KEY }}"

      - name: Check Response
        run: |
          if [ $? -ne 0 ]; then
            echo "Backup failed"
            exit 1
          fi
